<a href="https://colab.research.google.com/github/pratikgujral/Learn_LinearAlgebra/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import sympy

# Gaussian Elimination

Given a system of linear equations:  
$-x -y + 3z = 3$  
$x + z = 3$  
$3x -y + 7z = 15$

<br/>

This is solved by converting the system of equations to Row Echelon form.

Reduced Row Echelon Form can be computed using **`sympy.Matrix.rref()`**

In [5]:
A = sympy.Matrix([
                  [-1,-1,3,-3],
                  [1,0,1,-3],
                  [3,-1,7,-15]
                ])
A

Matrix([
[-1, -1, 3,  -3],
[ 1,  0, 1,  -3],
[ 3, -1, 7, -15]])

**`A.rref()`** returns the Reduced Row Echelon Form and also the index of the Pivot columns in `A`.

In [7]:
A_rref, pivot_col_indices = A.rref()

print(pivot_col_indices)
A_rref

(0, 1)


Matrix([
[1, 0,  1, -3],
[0, 1, -4,  6],
[0, 0,  0,  0]])

**Another Example...**  
Find the reduced row echelon form, and pivot columns of given system of equations.

NOTEL: The given system os equations represents a determined system.

In [8]:
A = sympy.Matrix([
                  [1,2,2,2],
                  [2,4,6,8],
                  [3,6,8,10]
])
A

Matrix([
[1, 2, 2,  2],
[2, 4, 6,  8],
[3, 6, 8, 10]])

In [9]:
A.rref()

(Matrix([
 [1, 2, 0, -2],
 [0, 0, 1,  2],
 [0, 0, 0,  0]]), (0, 2))

**Example of solving an overdermined system**

In [10]:
A = sympy.Matrix([
                  [1,2,3],
                  [2,4,6],
                  [2,8,10]
])
A

Matrix([
[1, 2,  3],
[2, 4,  6],
[2, 8, 10]])

NOTE: We do have 3 cols, but all 3 columns are not independent.   
$R_3 <= R_1 + R_2$ 

In [11]:
A.rref()

(Matrix([
 [1, 0, 1],
 [0, 1, 1],
 [0, 0, 0]]), (0, 1))

## Rank

Rank = # of pivot columns in A.

In [13]:
A.rank()

2

## Null Space of matrix

Null space of a matrix $A$ is defined as a set of all the vectors $X$ that satisfy $A.X=0$

Steps to compute null space:
1. Convert to reduced row echelon form using Gaussian Elimination
2. Pick any values for the free variables. So if we have two free variables `f1` and `f2`, we assume their values to be `(1, 0)` and `(0, 1)`. We don't choose `(0,0)` as that is a trivial; solution to $A.X=0$.

In [15]:
A.nullspace()

[Matrix([
 [-1],
 [-1],
 [ 1]])]

---

# Solving $A.X=B$

## Goal 
Check if a solution exists to a given system of equations, and if it does, find all those solutions.

<br/>

Example:
```
x + y + z = 1 
x + y + 2z = 3
```

This can be solved via Sympy in a variety of ways.

1. Augmented Matrix form
2. System of Equations
3. $A.x=b$ form

### Augmented Matrix Form

In [32]:
from sympy import Matrix, symbols
from sympy.solvers.solveset import linsolve

A = sympy.Matrix([
                  [1,1,1,1],
                  [1,1,2,3]
])

A

Matrix([
[1, 1, 1, 1],
[1, 1, 2, 3]])

In [34]:
# Create Sympy symbols for representing variables of the given system of equations
x, y, z = symbols('x y z')

linsolve(A, (x, y, z))

FiniteSet((-y - 1, y, 2))

### System of equations form

In [35]:
# Create Sympy symbols
x, y, z = symbols('x y z')

linsolve([x + y + z - 1, x + y + 2*z - 3 ], (x, y, z))

FiniteSet((-y - 1, y, 2))

### $A.x=b$ form

In [42]:
M = sympy.Matrix([
                  [1,1,1,1],
                  [1,1,2,3]
])

M

Matrix([
[1, 1, 1, 1],
[1, 1, 2, 3]])

In [44]:
system = A, b = M[:, :-1], M[:, -1]

print(A)
print(b)
print(system)

Matrix([[1, 1, 1], [1, 1, 2]])
Matrix([[1], [3]])
(Matrix([
[1, 1, 1],
[1, 1, 2]]), Matrix([
[1],
[3]]))


FiniteSet((-y - 1, y, 2))

In [45]:
linsolve(system, x, y, z)

FiniteSet((-y - 1, y, 2))

---
# Solving linear system of equations

$A.x = b$

We can use Gaussian elimination to solve the system of equations. However the time complexity of performing Gaussian Elimination is $O(n_3)$.  

If $A$ is a suare matrix, then there are couple of approximation techniques that can be used to speed up the solution.

In [3]:
import numpy as np

A = np.array([
             [3,2,1],
             [1,4,4],
             [3,2,8]
])

b = np.array([
              [8],
              [13],
              [15]
])

print(A)
print(b)

[[3 2 1]
 [1 4 4]
 [3 2 8]]
[[ 8]
 [13]
 [15]]


## Jacobi Iterations

$A = D + E$   

$A$ : (m * m) matrix  
$D$ : (m * m) matrix containing only diagonal elements of A  
$E$ : (m * m) matrix containing only non-diagonal elements of A


### Derivation
$b = Ax$  
$b = (D + E) x$  
$b = Dx + Ex$  
$Dx = -Ex + b$  
$x = -D^{-1}Ex + D^{-1}b$  


### Algorithm

- Initialize:
  $x = x_0$

- For kth iteration  
    $x_i^{k+1} = -\frac{1}{A_{ii}} (\sum\limits_{j \neq i} A_{ij} - b_i)$

- Find error
    


In [4]:
# Implement here

# Solving $|| b - Ax ||$

## Steepest Descent
### Theory
- https://towardsdatascience.com/descent-method-steepest-descent-and-conjugate-gradient-math-explained-78601d8df3ce
- https://sophiamyang.medium.com/descent-method-steepest-descent-and-conjugate-gradient-in-python-85aa4c4aac7b

### Algorithm
- Initialize
      x(0) = 0

- For `k=1` to `max_iter`:
      1. Find the residue at current position
         r(k) = b - Ax(k)

      2. Update step size α
         α = ( r(k).T x r(k) ) / ( r(k).T x A x r(k) )

      3. Take a step of size α in the direction of steepest descent 
         x(k+1) = x(k) + α r(k)
  End


In [17]:
def my_steepest_descent(A, b, max_iter=100):
  """
  A -> m x m
  b -> m x 1
  """

  # Get shapes. NOTE: A is a square matrix
  m, m = A.shape

  # Intialize. Since Ax = b => Shape(x) = m x 1, such that A(m,m)x(m,1) = b(m,1)
  x = np.zeros(shape=m)

  for i in range(max_iter):
    # Find residue. NOTE: Shape(r) = Shape(b) = Shape(Ax) = (m,1).
    r = b - A @ x

    # Step size. 
    """
    NOTE: As Shape(r) = (m,1) 
          => Shape(r.T) = (1,m)
          => Shape(r.T @ r) = (1,1)
        And  Shape(r.T @ A) = (1,m)
          => Shape(r.T @A @ r) = (1,m) x (m,1) = (1,1)
          => Shape(alpha) = (1,1)
    """
    alpha = (r.T @ r) / (r.T @ A @ r)

    # Update step
    x = x + alpha * r

  return x

### Evaluating

In [29]:
A = np.array([
             [3,2,1],
             [1,4,4],
             [3,2,8]
])

np.random.seed(7)

b = np.random.standard_normal(size=(3))

print(A)
print(A.shape)
print(b)
print(b.shape)

[[3 2 1]
 [1 4 4]
 [3 2 8]]
(3, 3)
[ 1.6905257  -0.46593737  0.03282016]
(3,)


Calling the steepest decent implementation function...

In [30]:
x = my_steepest_descent(A,b)
print(x)

[ 0.67467172 -0.0483372  -0.23681508]


This `x` should be the solution to `Ax = b`.

We can verify this by multiplying `A` and calculated `x` to check if we get back `b`. Ideally we should get back `b`, but since this solution is obtained through approximation, the value of `Ax` may not be exactly be equal to `b` but would be close enough.

In [31]:
A @ x

array([ 1.6905257 , -0.46593737,  0.03282016])

---

# Steepest Descent continued...
Our previous implementation of steepest descent required that the given system of equations should be determined, that is, $A$ should be a square matrix.

However, we may have over-determined (Tall $A_{m,n}$ ;  $m > n$) or under-determined (Wide $A_{m,n}$ ;  $m < n$) systems.

Hence, we will have to tweak our system $b=Ax$ such that, $A$ becomes a square matrix, and we can use the same solver(or function) for steepest descent that we used for determined system.

## Steepest descent for overdetermined system
For overdetermined system, $A_{m,n}$ such that $m>n$.  

$b_{m,1} = A_{m,n} x_{n,1}$

> $Ax = b$  
Multiply $A^T$ on both sides  
$A^T Ax = A^Tb$  

**Note**: $A$ = (m,n) => $A^T$ = (n,m) => $A^T A$ = (m,m)  
We successfully converted $A$ to a square matrix by multiplying it with $A^T$.


So for square systems,  
```
x = my_steepest_gradient(A, b)
```

But if A is not square,
```
x = my_steepest_gradient(A.T @ A, A.T @ b)
```

### Evaluating

In [45]:
A_under = np.array([
             [3,2,1,2],
             [1,4,4,5],
             [3,2,8,1]
])

np.random.seed(7)

b = np.random.standard_normal(size=(3))

print(A_under)
print(A_under.shape)
print(b)
print(b.shape)

[[3 2 1 2]
 [1 4 4 5]
 [3 2 8 1]]
(3, 4)
[ 1.6905257  -0.46593737  0.03282016]
(3,)


In [46]:
x = my_steepest_descent(A_under.T @ A_under, A_under.T @ b)
print(x)

[ 0.65783421  0.04703677 -0.24616324 -0.0654519 ]


Verifying that $Ax$ indeed produces value approximately equal to $b$

In [48]:
A_under @ x

array([ 1.69050914, -0.46593115,  0.03281839])

In [53]:
A_over = np.array([
             [3,2,1],
             [1,4,4],
             [3,2,8],
             [6,4,2]
])

b = np.array([10, 21, 31, 20])

print(A_over)
print(A_over.shape)
print(b)
print(b.shape)

[[3 2 1]
 [1 4 4]
 [3 2 8]
 [6 4 2]]
(4, 3)
[10 21 31 20]
(4,)


In [56]:
x = my_steepest_descent(A_over.T @ A_over, A_over.T @ b)
print(x)

[1.00005144 1.99991709 3.00000982]


Verifying that indeed A.x gives b

In [57]:
A_over @ x

array([ 9.99999831, 20.99975907, 31.00006701, 19.99999661])

---
---

## Conjugate Gradient

The steepest descent method is great that we minimize the function in the direction of each step. But it doesn’t guarantee that the direction we are going to minimize the function from all the previous directions.

Directions p are A conjugate directions if they have the following property (note A is symmetric positive definite):

> $P_0, P_1, P_2... P_{k-1}$, such that   
$P_i^T A P_i = 0$ for $i \ne j$

Only when the current direction p is A conjugate to all the previous directions, will the next data point minimize the function in the span of all previous directions.


### Calculating A conjugate
Remember that the steepest descent chose the steepest slope, which is also the residual (r) at each step. And we know that this is a good choice. How about we find an A-conjugate direction that’s the closest to the direction of the steepest descent, i.e., we minimize the 2-norm of the vector (r-p).

Current direction  = Current Residual + Last direction  
$P_{k} = r_k + \gamma_k P_{k-1}$

Because of the property of A-conjugate directions:
$P_i^T A P_i = 0$

We can then calculate $\gamma_k$ as :

$P_{k-1}^T A \gamma_k + \gamma P_{k-1}^T A P_{k-1} = 0$

Hence,  
> $\gamma_k = - \frac{P_{k-1}^T A \gamma_k}{P_{k-1}^T A P_{k-1}} $  


In [35]:
from numpy import linalg as LA

In [37]:
def is_pos_def(x):
  """check if a matrix is symmetric positive definite"""
  return np.all(np.linalg.eigvals(x) > 0)

In [94]:
def my_conjugate_gradient(A, b):
  # if (is_pos_def(A) == False) | (A != A.T).any():
    # raise ValueError('Matrix A needs to be symmetric positive definite (SPD)')
  
  # Initialize
  p = r = b
  k = 0
  x = np.zeros(A.shape[-1])

  # Can iterate for fixed number of times or until residue drops below threshold
  while LA.norm(r) > 1e-10 :
    if k == 0:
      pass
    else: 
      gamma = - (p @ A @ r)/(p @ A @ p)
      p = r + gamma * p
    
    # Calculate step size
    alpha = (p @ r) / (p @ A @ p)

    # Update step
    x = x + alpha * p
    # Update residue for next iteration
    r = r - alpha * (A @ p)
    k =+ 1
  return x

### Evaluate

In [74]:
A = np.array([
              [3,2],
              [2,3]
])

b = np.array([-2, 7])

print(A)
print(A.shape)
print(b)
print(b.shape)

[[3 2]
 [2 3]]
(2, 2)
[-2  7]
(2,)


In [75]:
x = my_conjugate_gradient(A.T @ A, A.T @ b)
print(x)

[-4.  5.]


Verifying...

In [76]:
A @ x

array([-2.,  7.])

If A is an overdetermined system

In [77]:
A_over = np.array([
             [3,2,1],
             [1,4,4],
             [3,2,8],
             [6,4,2]
])

b = np.array([10, 21, 31, 20])

print(A_over)
print(A_over.shape)
print(b)
print(b.shape)

[[3 2 1]
 [1 4 4]
 [3 2 8]
 [6 4 2]]
(4, 3)
[10 21 31 20]
(4,)


In [78]:
x = my_conjugate_gradient(A_over.T @ A_over, A_over.T @ b)
print(x)

[1. 2. 3.]


Verifying...

In [79]:
A_over @ x

array([10., 21., 31., 20.])

If A is an underdetermined system

In [120]:
A_under = np.array([
             [3,2,1,2],
             [1,4,4,5],
             [3,2,8,1]
])

np.random.seed(7)

b = np.array([12, 26, 32])

print(A_under)
print(A_under.shape)
print(b)
print(b.shape)

[[3 2 1 2]
 [1 4 4 5]
 [3 2 8 1]]
(3, 4)
[12 26 32]
(3,)


In [121]:
x = my_conjugate_gradient(A_under.T @ A_under, A_under.T @b)
print(x)

NameError: ignored

Veriying...

In [96]:
A_under @ x

array([12., 26., 32.])

---
---

# Weighted Least Squares Solver

In [98]:
import numpy as np

Least squares solver.

Solves for $Ax=b$. 

If A is square and full rank (that is the system is well-determined), then `np.linalg.lstsq` returns the exact solution. 

Else, if the system is overdetermined or under-determined, then approximate solution is computed by minimizing the L2 Norm of $\epsilon$, that is,   
$min_x || \epsilon ||_2$  
$=min_x || b - Ax ||_2$

In [100]:
def least_squares_solver(A, b):
  # Using Numpy
  x_np, residuals, rank, singular  = np.linalg.lstsq(A, b)

  return x_np, residuals, rank, singular

To compute Weighted Least Squares, we simply pass in the weighted matrices

Solution to $Ax=b$ can be found by minimizing $=min_x || b - Ax ||_2$ in `LS(A, b)`, where `LS` represents any least squares solver such as steepest descent or conjugate gradient..

But to solve 
$min_x ||W( b - Ax ) ||_2$  
$= min_x ||Wb - WAx ) ||_2$

So simply use `LS(WA, Wb)` to solve the system, where `LS` still represents the same linear solver.

### Iteratively Reweighted Least Squares (IRLS)

Using Numpy's approximate least squares solver for fixed number of iterations.

In [2]:
import numpy as np

In [7]:
def my_IRLS(A, b, max_iter=100):
  # Get dimensions
  m, n = A.shape # A is (m,n)

  # Initialize
  W = np.eye(n)
  print(W.shape)

  for i in range(max_iter):
    # Solve
    x,_,_,_ = np.linalg.lstsq(W @ (A.T @ A), W @ (A.T @ b))

    # Update weights
    W = np.fill_diagonal(W, 1/np.sqrt(x))

  return x

In [100]:
def my_IRLS(A, b, max_iter=100, delta=0.001):
  # Get dimensions
  m = A.shape[0] # A is (m,m)

  # Initialize
  W = np.eye(m)

  for i in range(max_iter):
    # Solve
    x,_,_,_ = np.linalg.lstsq(W @ A, W @ b, rcond=None)

    # Update weights
    np.fill_diagonal(W, 1/np.sqrt(b - A @ x + delta))
    # a small delta is added because b-Ax can yeild very small negative values.
    # Adding delta ensures that everythign inside sqrt remains +ve

  return x

#### For a determined system

In [101]:
A = np.array([
              [3,2],
              [2,3]
])

b = np.array([-2, 7])

print(A)
print(A.shape)
print(b)
print(b.shape)

[[3 2]
 [2 3]]
(2, 2)
[-2  7]
(2,)


In [102]:
x = my_IRLS(A, b)
print(x)

[-4.  5.]


Verifying...

In [103]:
print(b)
print(A @ x)

[-2  7]
[-2.  7.]


#### Over-determined system

In [104]:
A_over = np.array([
             [3,2,1],
             [1,4,4],
             [3,2,8],
             [6,4,2]
])

b = np.array([10, 21, 31, 20])

print(A_over)
print(A_over.shape)
print(b)
print(b.shape)

[[3 2 1]
 [1 4 4]
 [3 2 8]
 [6 4 2]]
(4, 3)
[10 21 31 20]
(4,)


If our least squares solver `LS` is only capable of solving determined systems (that is when A is a square matrix), we tweak our inputs to the solver as 

$x = LS (A, b) \mid A_{m,m}$  

If our $A$ is over-determined or underdetermined, we input   
$x = LS (A^T A, A^T b) \mid A_{m,n}$  

In [111]:
x = my_IRLS(A_over.T @ A_over, A_over.T @ b)
print(x)

[1. 2. 3.]


Verifying that the solution x we found indeed satisfies $Ax = b$:

In [112]:
print(b)
print(A_over @ x)

[10 21 31 20]
[10. 21. 31. 20.]


However, the Least Squares Solver that we're using from Numpy namely **`np.linalg.lstsq`** is internally capable of handling overdetermined, underdtermined and fully determined systems. So, actually we do not have to worry about first converting $A$ into a square matrix.

Verifying this by simply calling `my_IRLS(A_over, b)` instead of `my_IRLS(A_over.T @ A_over, A_over.T @ b)`

In [113]:
x = my_IRLS(A_over, b)
print(x)

[1. 2. 3.]


Verifying that the solution x we found indeed satisfies $Ax=b$ :

In [114]:
print(b)
print( A_over @ x )

[10 21 31 20]
[10. 21. 31. 20.]


#### Underdetermined systems

In [117]:
A_under = np.array([
             [3,2,1,2],
             [1,4,4,5],
             [3,2,8,1]
])

b = np.array([12, 26, 32])

print(A_under.shape)
print(b.shape)

(3, 4)
(3,)


Just like the case of overdetermined systems, if the Least Squares solver is capable of solving only sqaure (fully determined) systems, then we convert the inputs $A, b$ to square matrices such that $A \rightarrow A^T A$ and $b \rightarrow A^T b$

In [136]:
x = my_IRLS(A_under.T @ A_under, A_under.T @ b)
print(x)

[1.09842319 1.44226857 3.05467955 1.38275687]


In [137]:
x = my_IRLS(A_under, b)
print(x)

[1.09842319 1.44226857 3.05467955 1.38275687]


Verifying that the solution `x` we computed indeed satisfies $Ax=b$

In [138]:
print(b)
print(A_under @ x)

[12 26 32]
[12. 26. 32.]


But since, **`np.linalg.lstsq`** is internally capable of handling overdetermined, underdtermined and fully determined systems, we do not have to worry about first converting $A$ into a square matrix.

In [139]:
x = my_IRLS(A_under, b)
print(x)

[1.09842319 1.44226857 3.05467955 1.38275687]


Verifying that the solution `x` we computed indeed satisfies $Ax=b$

In [143]:
print(b)
print(A_under @ x)

[12 26 32]
[12. 26. 32.]


---
---